name: Sync Fork with Upstream Repository

on:
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次，时间可以根据需要调整
  workflow_dispatch:  # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          ref: main  # 替换为你的默认分支名称

      - name: Set up Git
        run: |
          git config --global user.name 'huangsh'
          git config --global user.email '942212756@qq.com'

      - name: Add upstream repository
        run: git remote add upstream https://github.com/wzdnzd/aggregator  # 替换为主仓库的URL

      - name: Fetch upstream
        run: git fetch upstream

      - name: Merge upstream/main into forked repository
        run: git merge upstream/main --allow-unrelated-histories

      - name: Push changes
        run: git push origin main
